# required properties
group = com.almostreliable
modId = kubejs_oritech
modName = KubeJS Oritech
modPackage = com.almostreliable.kubeoritech
modVersion = 0.4.4
minecraftVersion = 26.1.2
neoforgeVersion = 26.1.2.82

# replacement properties
modAuthor = Almost Reliable
modDescription = KubeJS integration for Oritech.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = kubejs_oritech

# mod dependencies
kjsVersion = 26.1.2-8.0.3
oritechVersion = 2.0.0-exp3

# settings
almostgradle.buildconfig = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 19.25.0.322

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
